#!/bin/bash

getSensorData_bin=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# timestamp directive is not set for this probe
timestampDirective=$1 && shift

delay=$1 && shift
count=$1 && shift

sql-collector \
    --connect $DB_CONNSTR \
    --query $getSensorData_bin/aiaflows.sql \
    --count $count \
    --interval $delay \
    --delimiter "$CSVdelimiter" \
    "$*" 

