#!/bin/bash

target=$@

ping_stats=$(timeout 10 ping -c5 $target | tail -1 | cut -f2 -d= | cut -d' ' -f2 | tr '/' ',')
if [ ! -z "$ping_stats" ]; then
    echo "$target,$ping_stats"
else
    echo "$target,-1,-1,-1,-1"
fi

#echo "$target,$(ping -c5 -W5 $target | tail -1 | cut -f2 -d= | cut -d' ' -f2 | tr '/' ',')"

