#!/bin/bash

echo dms-collector --loginform --noheader --count 1 --delay 1 $@ | tr -d '"' | cut -d, -f3-99999
dms-collector --loginform --noheader --count 1 --delay 1 $@ | tr -d '"' | cut -d, -f3-99999
