#!/bin/bash
# external loop is used to add proper timestmp to each measurement
count=$1; shift
delay=$1; shift

dms-collector --loginform --noheader --count 1 --delay 1 $@ | tr -d '"' | cut -d, -f3-99999
if [ "$dms_reset" == 'after_each_collection' ]; then
    $umcRoot/lib/soadms-service.sh $umc_svc_def reset-dms $dms_reset_path "Reset: $dms_reset" >/dev/null 2>&1
fi
