#!/bin/bash
# creates umc nodes to test umc
# requires umc-oel511 image

# the script directory
scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
UMC_HOME=$(cd $scriptDir && cd ../../../umc && pwd -P)
IMAGE="tomvit/umc-oel7:1.4"

docker rm umc-ukbn17hr --force

docker run -it --user oracle --net umcnet -h ukbn17hr.umc.local \
        -v $UMC_HOME:/home/oracle/umc \
        --name umc-ukbn17hr \
        --ip 192.168.10.117 -d $IMAGE /bin/bash -l
