# -*- mode: ruby -*-
# vi: set ft=ruby :

# This is the vagrant file for umc test machine based on Oracle Enterprise Linux 5.11
# in order to use this, you need to import the box as follows:
#
# 	vagrant box add --name oel511 http://cloud.terry.im/vagrant/oraclelinux-5-x86_64.box
#
Vagrant.configure("2") do |config|
  config.vm.box = "oel511"

  # this will map the umc root to the vagrant's home umc directory
  config.vm.synced_folder "../../", "/home/vagrant/umc"

  # network
  config.vm.network :private_network, ip: "192.168.10.101"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "umc_oel511_vm"
      vb.memory = "512"
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # set Europe/Prague timezone 
    sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Prague /etc/localtime

    # writes a line to bash_profile
    w2p () {
	echo $1 >>~/.bash_profile
    }

    # remove old logs directory 
    rm -fr ~/umc/test/oel-511/logs

    ~/umc/varia/bin/install-libs.sh --yes

    # other settings on user login
    echo "Writing misc settings to bash_profile" 
    w2p ""
    w2p "# various settings" 
    w2p "export LS_COLORS=''"
    w2p "alias ll='ls -all --color=always'"

    # initialize umc on user login
    echo "Writing umc settings to bash_profile"
    w2p ""
    w2p "# umc startup"
    w2p "source ~/libs/umc-libs-env.sh"
    w2p "source ~/umc/test/oel-511/umc-startup.sh"
 
  SHELL
  

end
