# -*- mode: ruby -*-
# vi: set ft=ruby :

# This is the vagrant file for umc test machine based on Oracle Enterprise Linux 5.11
# in order to use this, you need to import the box as follows:
#
# 	vagrant box add --name oel511 http://cloud.terry.im/vagrant/oraclelinux-5-x86_64.box
#
Vagrant.configure("2") do |config|
  config.vm.box = "oel511"

  # this will map the umc root to the vagrant's home umc directory
  config.vm.synced_folder "../../", "/home/vagrant/umc"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "umc_oel511_vm"
      vb.memory = "512"
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
	# install python 2.7.11 locally
        mkdir ~/python
        cd ~/python
        wget --progress=bar:force https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
        tar zxfv Python-2.7.11.tgz
        find ~/python -type d | xargs chmod 0755
	rm Python-2.7.11.tgz
        cd Python-2.7.11

        # build python binaries
        ./configure --prefix=$HOME/python
        make && make install

        # update environment variables 
        echo "" >>~/.bash_profile
	echo "# environment for local python" >>~/.bash_profile
	echo "export PATH=$HOME/python/Python-2.7.11/:$PATH" >>~/.bash_profile
        echo "export PYTHONPATH=$HOME/python/Python-2.7.11" >>~/.bash_profile
	echo "source $HOME/umc/bin/umc.h &>/dev/null" >>~/.bash_profile

        # umc scripts use python2 in shebang
	# hence reate a symbolic link for python2 to point to python 2.7.11
	cd $HOME/python/Python-2.7.11/
	ln -s python python2
         
  SHELL
  

end
