#!/bin/bash
# Tomas Vitvar, tomas@vitvar.com

# this script directory
getSensorData_bin=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# check umc was configured
if [ ! -d $umcRoot ]; then
  echo >&2 "umc was not initialized!"
  exit 1
fi

# configuration directory
configDir="$umcRoot/etc/tools/dms"

# the first parameter is timestamp directive
# since we do not use it, we skip it (the value is None)
shift

# the next arguments are delay, count, table and config
delay=$1 && shift
count=$1 && shift
events=$1 && shift
config=$1 && shift

if [ "$delay" -ne 0 ]; then
  echo >&2 "delay parameter must be 0 as dmsreset does not use it!"
  exit 1
fi

if [ -f "$configDir/$config" ]; then
	# load variables for this connection
	source $configDir/$config

	# use connection information from the configuration file
	dms-collector --count $count --runonevents $events --dmsreset / --url "$DMSCOLLECTOR_URL" --connect "$DMSCOLLECTOR_CONNECT" "$@"
else
	# when no configuration is provided, assume the url/connect will be provided as arguments
	dms-collector --count $count --runonevents $events "$@"
fi 


