#---------------------------------------------------------------------------------------
#--- platform location & specific configuration
#---------------------------------------------------------------------------------------

#TODO configure below variables to used Oracle SOA data collectors
export FMW_HOME=/oracle/fmwhome
export SOA_HOME=$FMW_HOME/Oracle_SOA1
export OSB_HOME=$FMW_HOME/Oracle_OSB1
export WLS_HOME=$FMW_HOME/wlserver_10.3/server
export DOMAIN_HOME=$FMW_HOME/user_projects/domains/dev_soasuite

#---------------------------------------------------------------------------------------
#--- reporting
#---------------------------------------------------------------------------------------

export CSVdelimiter=,

#---------------------------------------------------------------------------------------
#--- umcrunner and idbpush
#---------------------------------------------------------------------------------------

export UMC_ORG="acme"
export UMC_ENV="sample"

export UMC_LOG_DIR="$umcRoot/logs"
export PYTHONPATH=$PYTHONPATH:"$umcRoot/bin/libs"

export UMCRUNNER_CONFIG="$umcRoot/etc/umcrunner.conf.$UMC_ORG"

# source environment-specific configuration
# source "$umcRoot/etc/env.$UMC_ORG.$UMC_ENV"
