#!/bin/bash

delay=$1; shift
count=$1; shift
device=$1

count=$(( $count + 1 ))

if [ -z "$device" ]; then
    iostat -k -y -d $delay $count | 
    sed $sedBUFFER -n -e '/^Device:/,/^$/{ /^Device/d; /^$/d; p; }'  | 
    sed $sedBUFFER 's/  */,/g;s/^,//;s/,$//'
else
    iostat -k -y -p $device  -d $delay $count | 
    sed $sedBUFFER -n -e '/^Device:/,/^$/{ /^Device/d; /^$/d; p; }'  | 
    sed $sedBUFFER 's/  */,/g;s/^,//;s/,$//' | 
    egrep -v "$device[0-9]"
fi
