#!/bin/bash

#get interface name
netlist=$1

#if no parameter is specified get data from all interfeces
if [ -z $netlist ]; then
  netlist=ALL
fi

#extract interface names
if [ "$netlist" = "ALL" ]; then 
  netlist=$(ifconfig | grep "^[a-zA-Z]" | cut -d ':' -f1)
fi

#collect data for each interface
for net in $netlist; do 
   /sbin/ifconfig $net \
   | egrep 'RX|TX' \
   | perl $toolsBin/joinlines.pl -stop "TX errors" \
   | sed $sedBUFFER 's/[(),]//g' \
   | sed $sedBUFFER 's/  */,/g' \
   | cut -d ',' -f4,6,11,13,15,17,20,22,27,29,31,33,35 \
   | perl -ne "$perlBUFFER; print \"$net,\$_\";" \
   | sed 's/,,/,/g'
done

