#!/bin/bash

target=$@


ping_stats=$(ping -c5 -W2 $target | tail -1 | cut -f2 -d= | cut -d' ' -f2 | tr '/' ',')
case ${PIPESTATUS[0]} in
0)
    echo "$target,$ping_stats"
    ;;
*)
    echo "$target,-1,-1,-1,-1"
    ;;
esac

#echo "$target,$(ping -c5 -W5 $target | tail -1 | cut -f2 -d= | cut -d' ' -f2 | tr '/' ',')"

