#!/bin/bash

target=$@

sudo mtr -c 5 --report --report-wide $target | 
tail -1 | 
tr -s ' ' | 
sed 's/^ //' | 
tr ' ' ',' | 
sed 's/.,/,/' | 
tr -d % > /tmp/mtr.$target.tmp

echo "$target,$(cat /tmp/mtr.$target.tmp)"

rm /tmp/mtr.$target.tmp

